# -*- coding: utf-8 -*-
"""EfimovKalashnicov_step4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EATXSPxbKYiekQx7gBFJJ_AznBZAUUyM
"""

import math
# использовал только для вычисления корня 
a = list = []

print("Введите элементы строки")

for i in range(2):
  print("Строка:", i+1)
  a0 = input()
  b = a0.split(" ")
  a.append(b)
  for i in range(2):
    b[i] = int(b[i])

lam1 = (a[0][0]+a[1][1]+math.sqrt((a[0][0]+a[1][1])*(a[0][0]+a[1][1])-4*(a[0][0]*a[1][1]-a[0][1]*a[1][0])))/2
lam2 = (a[0][0]+a[1][1]-math.sqrt((a[0][0]+a[1][1])*(a[0][0]+a[1][1])-4*(a[0][0]*a[1][1]-a[0][1]*a[1][0])))/2

lams = list = []


print("Собственные значения:")

lams.append(lam1)
lams.append(lam2)
print(lams)

# 
xy = list = []
b = list = []
# lams
for i in range(2):
  l = lams[i]
  if a[0][0]-l == 0 and a[0][1] == 0:
    if a[1][0] != 0 and a[1][1] != 0:
      c = -1*(a[1][0])/(a[1][1]-l)
      b.append(1)
      b.append(c)
      xy.append(b)
      b = list = []
      break
    elif a[1][0] == 0:
      b.append(1)
      b.append(0)
      xy.append(b)
      b = list = []
      break
    elif a[1][1] == 0:
      b.append(0)
      b.append(1)
      xy.append(b)
      b = list = []
      break
  
  if a[1][0] == 0 and a[1][1]-l == 0:
    if a[0][0]-l != 0 and a[0][1] != 0:
      c = -1*(a[0][0]-l)/(a[0][1])
      b.append(1)
      b.append(c)
      xy.append(b)
      b = list = []
      break
    elif a[0][0] == 0:
      b.append(1)
      b.append(0)
      xy.append(b)
      b = list = []
      break
    elif a[0][1] == 0:
      b.append(0) 
      b.append(1)
      xy.append(b)
      b = list = []
      break
  c = -1*((a[0][0]-l+a[1][0])/(a[0][1]+a[1][1]-l))
  b.append(1)
  b.append(c)
  xy.append(b)
  b = list = []
print("Вектора:")
print(xy)