# -*- coding: utf-8 -*-
"""linal_step3_EfimovKalashnicov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1801WieUmUq3FWkT-ciKESTYL5zZ1lStI
"""

a = list = []

print("Вводите элементы строки через пробел")

for i in range(3):
  print("Строка:", i+1)
  a0 = str(input())
  b = a0.split(" ")
  a.append(b)
  for i in range(3):
    b[i] = float(b[i])

c1 = str(-1)+"xxx"

c2 = a[1][1]+a[2][2]+a[0][0]

def pl(c):
  if c > 0:
    c = "+" + str(c)
  else:
    c = str(c)
  return c

c2 = pl(c2)+"xx"

c3 = -1*(a[0][0]*(a[1][1]+a[2][2])+a[1][1]*a[2][2]-a[1][2]*a[2][1]-a[2][0]*a[0][2]-a[0][1]*a[1][0])
c3 = pl(c3)+"x"

c4 = a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1]) + a[0][1]*(a[1][2]*a[2][0]-a[1][0]*a[2][2]) + a[0][2]*(a[1][0]*a[2][1]-a[2][0]*a[1][1])
c4 = pl(c4)

print("Характеристическое уравнение матрицы:", a, ":")
print(c1+c2+c3+c4+"=0")